# -*- coding: utf-8 -*-
"""PredictWithCSV.ipynb

Automatically generated by Colaboratory.

data from: https://www.kaggle.com/datasets/vikramtiwari/california-housing-dataset-ml-crash-course
"""

import pandas as pd

datos = pd.read_csv('../data/california_housing_train.csv')

print(datos)

from sklearn.preprocessing import StandardScaler
import numpy as np

scaler = StandardScaler()

print(np.mean(datos.loc[:,'total_rooms']))
scaler.fit(datos)
datos = scaler.transform(datos)

# np.mean(scaler.transform(datos)[:,4])

np.mean(datos.loc[:,'total_rooms'])

from sklearn.svm import SVR

model = SVR(C=1.0, epsilon=0.2)

model.fit(X=datos[:,0:4], y=datos[:,-1])

import pickle as pk

pickle_file = open('/content/sample_data/modelo', 'wb')
pk.dump(model, pickle_file)

# modelo.predict()  Para predecir

pickle_file = open('/content/sample_data/modelo', 'rb')
modelo = pk.load(pickle_file)